
import java.awt.Point;
import javax.swing.event.ListSelectionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dfernandezguerreiro
 */
public class Boletin_25 extends javax.swing.JFrame {

    /**
     * Creates new form Boletin_25
     */
    public Boletin_25() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jText1 = new javax.swing.JTextField();
        jText2 = new javax.swing.JTextField();
        jText3 = new javax.swing.JTextField();
        etSelecciona = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "10", "20", "30", "40"},
                {"1", "11", "21", "31", "41"},
                {"2", "12", "22", "32", "42"},
                {"3", "13", "23", "33", "43"},
                {"4", "14", "24", "34", "44"},
                {"5", "15", "25", "35", "45"},
                {"6", "16", "26", "36", "46"},
                {"7", "17", "27", "37", "47"},
                {"8", "18", "28", "38", "48"},
                {"9", "19", "29", "39", "49"}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jText1.setText("(números seleccionados)");
        jText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText1MouseClicked(evt);
            }
        });
        jText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText1ActionPerformed(evt);
            }
        });

        jText2.setText("(números ganadores)");
        jText2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText2MouseClicked(evt);
            }
        });
        jText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText2ActionPerformed(evt);
            }
        });

        jText3.setText("(número de aciertos)");
        jText3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText3MouseClicked(evt);
            }
        });
        jText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText3ActionPerformed(evt);
            }
        });

        etSelecciona.setText("Selecciona 6 números:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etSelecciona))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jText1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jText2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(etSelecciona)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String numero=null,completo="";
    String[]numeros=new String[6];
    int i=0;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Para seleccionar una celda de la tabla:
        Point pr=this.jTable1.getMousePosition();
        int row=this.jTable1.rowAtPoint(pr);
        int colum=this.jTable1.columnAtPoint(pr);
        
        numero=(String) this.jTable1.getValueAt(row, colum);
        
        numeros[i]=numero;
        completo=completo+numero+" ";
        jText1.setText(completo);
        i++;
        
        if(i==6){
            System.out.println("Ya has seleccionado 6 números.");
            numAleatorios();
            compararNum();
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    int numAleatorio;
    String completoNumAle="";
    int[]numAlea=new int[6];
    public void numAleatorios(){
        for(int i=0;i<numAlea.length;i++){
            numAlea[i]=(int) (Math.floor(Math.random()*49)+1); // Math.floor(): Para no generar números iguales.
            System.out.println(numAlea[i]);
            numAleatorio=numAlea[i];
            completoNumAle=completoNumAle+numAlea[i]+" ";
            jText2.setText(completoNumAle);
        }
        
    }
    
    public void compararNum(){
        int contaAcertos=0;
        for(int i=0;i<numAlea.length;i++){
            if(numAlea[i]==Integer.parseInt(numeros[0])){
                System.out.println("1º GANADOR");
                contaAcertos++;
            }
            if(numAlea[i]==Integer.parseInt(numeros[1])){
                System.out.println("2º GANADOR");
                contaAcertos++;
            }
            if(numAlea[i]==Integer.parseInt(numeros[2])){
                System.out.println("3º GANADOR");
                contaAcertos++;
            }
            if(numAlea[i]==Integer.parseInt(numeros[3])){
                System.out.println("4º GANADOR");
                contaAcertos++;
            }
            if(numAlea[i]==Integer.parseInt(numeros[4])){
                System.out.println("5º GANADOR");
                contaAcertos++;
            }
            if(numAlea[i]==Integer.parseInt(numeros[5])){
                System.out.println("6º GANADOR");
                contaAcertos++;
            }
        }
        jText3.setText("Nº acertados: "+contaAcertos);
        
    }
    
    
    private void jText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText2ActionPerformed
        
    }//GEN-LAST:event_jText2ActionPerformed

    private void jText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText3ActionPerformed

    private void jText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText1ActionPerformed

    }//GEN-LAST:event_jText1ActionPerformed

    private void jText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText1MouseClicked
        //Evento: MouseClicked, para que al hacer click se ejecute lo siguiente y no deje modificar el campo.
        jText1.setEditable(false);
    }//GEN-LAST:event_jText1MouseClicked

    private void jText2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText2MouseClicked
        //Evento: MouseClicked, para que al hacer click se ejecute lo siguiente y no deje modificar el campo.
        jText2.setEditable(false);
    }//GEN-LAST:event_jText2MouseClicked

    private void jText3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText3MouseClicked
        //Evento: MouseClicked, para que al hacer click se ejecute lo siguiente y no deje modificar el campo.
        jText1.setEditable(false);
    }//GEN-LAST:event_jText3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boletin_25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boletin_25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boletin_25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boletin_25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boletin_25().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etSelecciona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText3;
    // End of variables declaration//GEN-END:variables
}
